export const SUBURBS: { slug: string; name: string; region: string; postcode: string }[] = [
  { slug: "thomastown", name: "Thomastown", region: "Northern Suburbs", postcode: "3074" },
  { slug: "brunswick", name: "Brunswick", region: "Inner North", postcode: "3056" },
  { slug: "richmond", name: "Richmond", region: "Inner East", postcode: "3121" },
  { slug: "carlton", name: "Carlton", region: "Inner North", postcode: "3053" },
  { slug: "st-kilda", name: "St Kilda", region: "Inner South", postcode: "3182" },
  { slug: "doncaster", name: "Doncaster", region: "Eastern Suburbs", postcode: "3108" },
  { slug: "ringwood", name: "Ringwood", region: "Eastern Suburbs", postcode: "3134" },
  { slug: "frankston", name: "Frankston", region: "Mornington Peninsula", postcode: "3199" },
  { slug: "dandenong", name: "Dandenong", region: "South-East", postcode: "3175" },
  { slug: "footscray", name: "Footscray", region: "Inner West", postcode: "3011" },
  { slug: "fitzroy", name: "Fitzroy", region: "Inner North", postcode: "3065" },
  { slug: "collingwood", name: "Collingwood", region: "Inner North", postcode: "3066" },
  { slug: "south-yarra", name: "South Yarra", region: "Inner South", postcode: "3141" },
  { slug: "prahran", name: "Prahran", region: "Inner South", postcode: "3181" },
  { slug: "hawthorn", name: "Hawthorn", region: "Inner East", postcode: "3122" },
  { slug: "glen-waverley", name: "Glen Waverley", region: "Eastern Suburbs", postcode: "3150" },
  { slug: "box-hill", name: "Box Hill", region: "Eastern Suburbs", postcode: "3128" },
  { slug: "moorabbin", name: "Moorabbin", region: "Bayside", postcode: "3189" },
  { slug: "essendon", name: "Essendon", region: "Northern Suburbs", postcode: "3040" },
  { slug: "coburg", name: "Coburg", region: "Northern Suburbs", postcode: "3058" },
  { slug: "heidelberg", name: "Heidelberg", region: "North-East", postcode: "3084" },
  { slug: "balwyn", name: "Balwyn", region: "Eastern Suburbs", postcode: "3103" },
  { slug: "glen-iris", name: "Glen Iris", region: "Inner East", postcode: "3146" },
  { slug: "camberwell", name: "Camberwell", region: "Inner East", postcode: "3124" },
  { slug: "nunawading", name: "Nunawading", region: "Eastern Suburbs", postcode: "3131" },
  { slug: "craigieburn", name: "Craigieburn", region: "Northern Growth Corridor", postcode: "3064" },
  { slug: "point-cook", name: "Point Cook", region: "Western Suburbs", postcode: "3030" },
  { slug: "werribee", name: "Werribee", region: "Western Suburbs", postcode: "3030" },
  { slug: "sunshine", name: "Sunshine", region: "Western Suburbs", postcode: "3020" },
  { slug: "melton", name: "Melton", region: "Western Growth Corridor", postcode: "3337" },
];
